routes/web.php
<?php

use App\Http\Middleware\LocaleMiddleware;
use Illuminate\Support\Facades\Route;

/* @var $localeMiddleware LocaleMiddleware */
$localeMiddleware = app( LocaleMiddleware::class);

\Illuminate\Support\Facades\Auth::routes();

Route::get('/admin/cache-clear',function (){
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');

    return redirect()->back()->with('success','Кеш успешно очищено!');
})->name('cache-clear');

Route::get('/admin/rename-index',function (){
//   $oldTagNameUk = "Індекс АПК";
//   $oldTagNameRu = "Индекс АПК";
//   $replaceUk = "Регіони";
//   $replaceRu = "Регионы";
//
//   $modelUk = \App\Models\Translations\BlogArticleTranslation::query()
//       ->where('tags','like','%'.$oldTagNameUk.'%')
//       ->get();
//
//   foreach ($modelUk as $item){
//       $tags = $item->tags;
//       $item->tags = mb_str_replace($oldTagNameUk,$replaceUk,$tags);
//       $item->save();
//   }
//
//    $modelRu = \App\Models\Translations\BlogArticleTranslation::query()
//        ->where('tags','like','%'.$oldTagNameRu.'%')
//        ->get();
//
//    foreach ($modelRu as $item){
//        $tags = $item->tags;
//        $item->tags = mb_str_replace($oldTagNameRu,$replaceRu,$tags);
//        $item->save();
//    }
//
//    dd('Ready');

});

//Route::get('rss-generate', function (){
//    \Illuminate\Support\Facades\Artisan::call('rss:generate');
//
//    dd('RSS is generated!');
//});
//
//Route::get('sitemap-gen',function (){
//    \Illuminate\Support\Facades\Artisan::call('sitemap:generate');
//    dd('ready');
//});
//
//Route::get('article-alt-generate',function (){
//    \Illuminate\Support\Facades\Artisan::call('altEmpty:generate');
//    dd('ready');
//});
//
//Route::get('parser-meta-tags-start',function (){
//    \Illuminate\Support\Facades\Artisan::call('ParserMetaTags:start');
//    dd('ready');
//});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::any('/admin/login', [\App\Http\Controllers\Admin\HomeController::class,'login'])->name('admin.login');

/*********************************************** ADMIN ****************************************************************/
Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function () {
    Route::post('/export-table', [\App\Http\Controllers\Admin\ExportTableController::class,'export'])->name('export-table');
    Route::get('/', [\App\Http\Controllers\Admin\HomeController::class,'index'])->name('admin');
    Route::resource('/users-admin', \App\Http\Controllers\Admin\UserAdminController::class);
    Route::resource('/access-groups', \App\Http\Controllers\Admin\AccessGroupsController::class);
    Route::get('/users/{id}/{tab}', [\App\Http\Controllers\Admin\UsersController::class,'getTab'])->where('tab', '[a-z0-9-]+');
    Route::post('/users-change-status', [\App\Http\Controllers\Admin\UsersController::class,'changeStatus'])->name('user.change-status');
    Route::resource('/users', \App\Http\Controllers\Admin\UsersController::class);
    Route::post('/pages/menu/add-item', [\App\Http\Controllers\Admin\PagesController::class,'addItem'])->name('page.add-item');
    Route::resource('/pages', \App\Http\Controllers\Admin\PagesController::class);
    Route::post('menu/toggle-collapse', [\App\Http\Controllers\Admin\MenuController::class,'toggleCollapse'])->name('menu.toggle-collapse');
    Route::post('menu/move', [\App\Http\Controllers\Admin\MenuController::class,'move']);
    Route::post('menu/rebuild', [\App\Http\Controllers\Admin\MenuController::class,'rebuild']);
    Route::post('menu/add-item', [\App\Http\Controllers\Admin\MenuController::class,'addItem'])->name('menu.add-item');
    Route::post('menu/delete-menu', [\App\Http\Controllers\Admin\MenuController::class,'deleteMenu'])->name('menu.delete-menu');
    Route::post('menu/add-menu', [\App\Http\Controllers\Admin\MenuController::class,'addMenu'])->name('menu.add-menu');
    Route::resource('/menu', \App\Http\Controllers\Admin\MenuController::class);
    Route::resource('/faq', \App\Http\Controllers\Admin\FaqController::class);
    Route::get('settings/{tab}', [\App\Http\Controllers\Admin\SettingsController::class,'index'])->name('add-notice')->where('tab', '[a-z0-9-]+');
    Route::post('settings/save', [\App\Http\Controllers\Admin\SettingsController::class,'save'])->name('settings.save');
    Route::post('/request/status/change', [\App\Http\Controllers\Admin\RequestController::class,'changeStatus'])->name('request.status-change');
    Route::resource('/request', \App\Http\Controllers\Admin\RequestController::class);

    Route::post('/bloggers/delete-selected', [\App\Http\Controllers\Admin\BloggersController::class,'deleteSelected'])->name('bloggers.delete-selected');
    Route::resource('/bloggers', \App\Http\Controllers\Admin\BloggersController::class);

    Route::post('/remove-item-block', [\App\Http\Controllers\Admin\BannersController::class,'removeItem'])->name('banners.remove-item');
    Route::post('/banners/add-empty-item', [\App\Http\Controllers\Admin\BannersController::class,'addEmptyItem'])->name('banner.add-empty-item');
    Route::post('/banner-stat/export', [\App\Http\Controllers\Admin\AnalyticsController::class,'export'])->name('banner-stat.export');
    Route::resource('/banner-stat', \App\Http\Controllers\Admin\AnalyticsController::class);
    Route::resource('/banners', \App\Http\Controllers\Admin\BannersController::class);

    /** BLOG **/
    Route::post('/categories/collapse', [\App\Http\Controllers\Admin\CategoriesController::class,'collapse'])->name('set-collapse');
    Route::resource('/categories', \App\Http\Controllers\Admin\CategoriesController::class);
    Route::get('/category/articles-create-with-category', [\App\Http\Controllers\Admin\CategoriesController::class,'createArticleWithCategory'])->name('articles.create-with-category');
    Route::get('/category/{path}/{sub?}', [\App\Http\Controllers\Admin\CategoriesController::class,'category'])->where('path', '[a-z0-9-]+')->where('sub', '[a-z0-9-]+');
    Route::group(['prefix' => 'blog'], function () {
        Route::resource('/tags', \App\Http\Controllers\Admin\BlogTagsController::class);
        Route::post('/articles/delete-selected', [\App\Http\Controllers\Admin\BlogArticlesController::class,'deleteSelected'])->name('articles.delete-selected');
        Route::get('/article/search',[\App\Http\Controllers\Admin\BlogArticlesController::class,'search'])->name('article.search');

        Route::post('/articles/delete-gallery', [\App\Http\Controllers\Admin\BlogArticlesController::class,'deleteFromGallery'])->name('articles.delete-gallery');
        Route::post('/articles/add-gallery', [\App\Http\Controllers\Admin\BlogArticlesController::class,'addGallery'])->name('articles.add-gallery');
        Route::resource('/articles', \App\Http\Controllers\Admin\BlogArticlesController::class);
        Route::delete('/subscribe/delete', [\App\Http\Controllers\Admin\BlogSubscribeController::class, 'delete'])->name('subscribe.delete');
        Route::get('/subscribe/list', [\App\Http\Controllers\Admin\BlogSubscribeController::class,'list'])->name('subscribe.list');
    });

    Route::get('/subscribe', [\App\Http\Controllers\Admin\BlogSubscribeController::class,'index'])->name('subscribe.index');

    Route::get('/tag/binding',[\App\Http\Controllers\Admin\TagsController::class,'binding'])->name('tag.binding');
    Route::post('/tag/tie',[\App\Http\Controllers\Admin\TagsController::class,'tie'])->name('tag.tie');
    Route::get('/tag/search',[\App\Http\Controllers\Admin\TagsController::class,'search'])->name('tags.search');
    Route::resource('/tag',\App\Http\Controllers\Admin\TagsController::class);

    Route::get('/multimedia/files',[\App\Http\Controllers\Admin\FileManagerController::class,'file'])->name('multimedia.files');
    Route::get('/multimedia/images',[\App\Http\Controllers\Admin\FileManagerController::class,'image'])->name('multimedia.images');

    Route::get('/landing/search',[\App\Http\Controllers\Admin\LandingController::class,'search'])->name('landing.search');
    Route::resource('/landing', \App\Http\Controllers\Admin\LandingController::class);
});
/************************************ END ADMIN ***********************************************************************/

Route::group(['namespace' => 'Front'], function(){
    Route::get('/rss/{id}', [\App\Http\Controllers\Front\RssController::class,'indexUk']);
    Route::get('/sitemap.xml', [\App\Http\Controllers\Front\RssController::class,'sitemap']);
    Route::get('{lang}/rss/{id}', [\App\Http\Controllers\Front\RssController::class,'index']);
    Route::any('/tg/{id}', [\App\Http\Controllers\Front\AdController::class,'index'])->where('id', '^(?!api).*$');

    Route::any('/{any}', [\App\Http\Controllers\Front\HomeController::class,'index'])->where('any', '^(?!api).*$')->name('home');
});
/*******************************************************************/

resources/views/admin/access/groups/_form.blade.php
@if($action === 'create')
    <form class="form-horizontal" method="POST" action="{{ route('access-groups.store') }}">
@elseif($action === 'edit')
    <form action="{{route('access-groups.update', $model->id)}}" class="form-horizontal" method="post">
        @method('PUT')
@endif
    @csrf
        <div class="card">

            <div class="card-header">
                <ul class="nav nav-tabs" id="myTab" role="tablist" style="margin-bottom: -10px;border-bottom: none">
                    <li class="nav-item">
                        <a class="nav-link active" id="main-tab" data-toggle="tab" href="#main" role="tab" aria-controls="main" aria-selected="true">Информация</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="permission-tab" data-toggle="tab" href="#permission" role="tab" aria-controls="permission" aria-selected="false">Привилегии</a>
                    </li>
                </ul>
            </div>

            <div class="card-body">
                <div class="tab-content" id="myTabContent">
                    {{----------------------------- MAIN TAB -----------------------------------------}}
                    <div class="tab-pane fade show active" id="main" role="tabpanel" aria-labelledby="main-tab">
                        @include('admin.access.groups.tabs._main',[
                            'model' => $model, 'action' => $action
                        ])
                    </div>

                    {{----------------------------- SEO TAB -----------------------------------------}}
                    <div class="tab-pane fade" id="permission" role="tabpanel" aria-labelledby="permission-tab">
                        @include('admin.access.groups.tabs._pemission',[
                            'model' => $model, 'action' => $action
                        ])
                    </div>
                </div>

                <input type="submit" value="Сохранить" class="btn btn-success text-white float-right">

            </div>
        </div>


{{--        <div class="form-group row">--}}
{{--            <label class="col-md-3 text-right" for="name"><span style="color:red">*</span>Ім'я</label>--}}
{{--            <div class="col-md-9">--}}
{{--                <input type="text" name="name" id="name" class="form-control" value="{{$model->name}}">--}}
{{--            </div>--}}
{{--        </div>--}}

{{--        <div class="form-group row">--}}
{{--            <label class="col-md-3 text-right" for="email"><span style="color:red">*</span> E-mail</label>--}}
{{--            <div class="col-md-9">--}}
{{--                <input type="text" name="email" id="email" class="form-control" value="{{$model->email}}">--}}
{{--            </div>--}}
{{--        </div>--}}

{{--        <div class="form-group row">--}}
{{--            <label class="col-md-3 text-right" for="phone">Телефон</label>--}}
{{--            <div class="col-md-9">--}}
{{--                <input type="text" name="phone" id="phone" class="form-control" value="{{$model->phone}}">--}}
{{--            </div>--}}
{{--        </div>--}}

{{--        <div class="form-group row">--}}
{{--            <label class="col-md-3 text-right" for="password">--}}
{{--                @if(! $model->id)--}}
{{--                <span style="color:red">*</span>--}}
{{--                @endif--}}
{{--                Пароль</label>--}}
{{--            <div class="col-md-9">--}}
{{--                <input type="password" name="password" id="password" class="form-control">--}}
{{--            </div>--}}
{{--        </div>--}}

{{--        <input type="submit" class="btn btn-success text-white" value="Зберегти">--}}
</form>

@push('scripts')
    <script>
        $(document).ready(() => {

        });
    </script>
@endpush

resources/views/admin/access/groups/create.blade.php
@extends('layouts.admin.app')

@section('content')
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('admin')}}">Панель управления</a></li>
            <li class="breadcrumb-item"><a href="{{route('access-groups.index')}}">Группы пользователей</a></li>
            <li class="breadcrumb-item active" aria-current="page">Добавить</li>
        </ol>
    </nav>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                @include('admin.access.groups._form',['model' => $model, 'action' => 'create'])
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/access/groups/edit.blade.php
@extends('layouts.admin.app')

@section('content')
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('admin')}}">Панель управления</a></li>
            <li class="breadcrumb-item"><a href="{{route('access-groups.index')}}">Группы пользователей</a></li>
            <li class="breadcrumb-item active" aria-current="page">Редактировать</li>
        </ol>
    </nav>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                @include('admin.access.groups._form',['model' => $model, 'action' => 'edit'])
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/access/groups/index.blade.php
@extends('layouts.admin.app')

@section('content')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('admin')}}">Панель управления</a></li>
            <li class="breadcrumb-item active" aria-current="page">Группы пользователей</li>
        </ol>
    </nav>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                @permission('admins__user_groups__create')
                    <a href="{{route('access-groups.create')}}" class="btn btn-primary float-right">
                        <i class="fa fa-plus"></i>
                        Добавить
                    </a>
                @endpermission
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Название</th>
                            <th>Код</th>
                            <th style="width: 150px"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($model as $item)
                            <tr data-id="{{$item->id}}">
                                <td>
                                    @permission('admins__user_groups__edit')
                                    <a href="{{ route('access-groups.edit', $item->id) }}" title="Редактировать">
                                        {{$item->name}}
                                    </a>
                                    @else
                                        {{$item->name}}
                                    @endpermission
                                </td>
                                <td>{{$item->code}}</td>
                                <td>
                                    <div style="display: flex">
                                        <div style="margin-left: 10px">
                                            <form action="{{ route('access-groups.destroy', $item->id) }}" method="POST">

                                                @permission('admins__user_groups__edit')
                                                <a href="{{ route('access-groups.edit', $item->id) }}" class="btn btn-primary text-white btn-xs" title="Редактировать">
                                                    <i class="fas fa-edit  fa-lg"></i>
                                                </a>
                                                @endpermission&nbsp;

                                                @csrf
                                                @method('DELETE')

                                                @permission('admins__user_groups__delete')
                                                <a href="javascript:void(0)" title="Удалить" class="btn btn-danger delete-item-btn text-white btn-xs">
                                                    <i class="fas fa-trash"></i>
                                                </a>
                                                @endpermission&nbsp;
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

                {{ $model->appends(request()->all())->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

@push('styles')
    <style>
        nav.breadcrumb-nav {
            position: relative;
        }
        nav.breadcrumb-nav a.btn {
            position: absolute;
            right: 15px;
            top: 4px;
        }
    </style>
@endpush

@push('scripts')
    <script>
        $(document).ready(() => {
            $('.delete-item-btn').on('click',function() {
                if(confirm('You definitely want to delete the user?')){
                    $(this).closest('form').submit();
                }
            });
        });
    </script>
@endpush