routes/web.php
<?php

use App\Http\Middleware\LocaleMiddleware;
use Illuminate\Support\Facades\Route;

/* @var $localeMiddleware LocaleMiddleware */
$localeMiddleware = app( LocaleMiddleware::class);

\Illuminate\Support\Facades\Auth::routes();

Route::get('/admin/cache-clear',function (){
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');

    return redirect()->back()->with('success','Кеш успешно очищено!');
})->name('cache-clear');

Route::get('/admin/rename-index',function (){
//   $oldTagNameUk = "Індекс АПК";
//   $oldTagNameRu = "Индекс АПК";
//   $replaceUk = "Регіони";
//   $replaceRu = "Регионы";
//
//   $modelUk = \App\Models\Translations\BlogArticleTranslation::query()
//       ->where('tags','like','%'.$oldTagNameUk.'%')
//       ->get();
//
//   foreach ($modelUk as $item){
//       $tags = $item->tags;
//       $item->tags = mb_str_replace($oldTagNameUk,$replaceUk,$tags);
//       $item->save();
//   }
//
//    $modelRu = \App\Models\Translations\BlogArticleTranslation::query()
//        ->where('tags','like','%'.$oldTagNameRu.'%')
//        ->get();
//
//    foreach ($modelRu as $item){
//        $tags = $item->tags;
//        $item->tags = mb_str_replace($oldTagNameRu,$replaceRu,$tags);
//        $item->save();
//    }
//
//    dd('Ready');

});

//Route::get('rss-generate', function (){
//    \Illuminate\Support\Facades\Artisan::call('rss:generate');
//
//    dd('RSS is generated!');
//});
//
//Route::get('sitemap-gen',function (){
//    \Illuminate\Support\Facades\Artisan::call('sitemap:generate');
//    dd('ready');
//});
//
//Route::get('article-alt-generate',function (){
//    \Illuminate\Support\Facades\Artisan::call('altEmpty:generate');
//    dd('ready');
//});
//
//Route::get('parser-meta-tags-start',function (){
//    \Illuminate\Support\Facades\Artisan::call('ParserMetaTags:start');
//    dd('ready');
//});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::any('/admin/login', [\App\Http\Controllers\Admin\HomeController::class,'login'])->name('admin.login');

/*********************************************** ADMIN ****************************************************************/
Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function () {
    Route::post('/export-table', [\App\Http\Controllers\Admin\ExportTableController::class,'export'])->name('export-table');
    Route::get('/', [\App\Http\Controllers\Admin\HomeController::class,'index'])->name('admin');
    Route::resource('/users-admin', \App\Http\Controllers\Admin\UserAdminController::class);
    Route::resource('/access-groups', \App\Http\Controllers\Admin\AccessGroupsController::class);
    Route::get('/users/{id}/{tab}', [\App\Http\Controllers\Admin\UsersController::class,'getTab'])->where('tab', '[a-z0-9-]+');
    Route::post('/users-change-status', [\App\Http\Controllers\Admin\UsersController::class,'changeStatus'])->name('user.change-status');
    Route::resource('/users', \App\Http\Controllers\Admin\UsersController::class);
    Route::post('/pages/menu/add-item', [\App\Http\Controllers\Admin\PagesController::class,'addItem'])->name('page.add-item');
    Route::resource('/pages', \App\Http\Controllers\Admin\PagesController::class);
    Route::post('menu/toggle-collapse', [\App\Http\Controllers\Admin\MenuController::class,'toggleCollapse'])->name('menu.toggle-collapse');
    Route::post('menu/move', [\App\Http\Controllers\Admin\MenuController::class,'move']);
    Route::post('menu/rebuild', [\App\Http\Controllers\Admin\MenuController::class,'rebuild']);
    Route::post('menu/add-item', [\App\Http\Controllers\Admin\MenuController::class,'addItem'])->name('menu.add-item');
    Route::post('menu/delete-menu', [\App\Http\Controllers\Admin\MenuController::class,'deleteMenu'])->name('menu.delete-menu');
    Route::post('menu/add-menu', [\App\Http\Controllers\Admin\MenuController::class,'addMenu'])->name('menu.add-menu');
    Route::resource('/menu', \App\Http\Controllers\Admin\MenuController::class);
    Route::resource('/faq', \App\Http\Controllers\Admin\FaqController::class);
    Route::get('settings/{tab}', [\App\Http\Controllers\Admin\SettingsController::class,'index'])->name('add-notice')->where('tab', '[a-z0-9-]+');
    Route::post('settings/save', [\App\Http\Controllers\Admin\SettingsController::class,'save'])->name('settings.save');
    Route::post('/request/status/change', [\App\Http\Controllers\Admin\RequestController::class,'changeStatus'])->name('request.status-change');
    Route::resource('/request', \App\Http\Controllers\Admin\RequestController::class);

    Route::post('/bloggers/delete-selected', [\App\Http\Controllers\Admin\BloggersController::class,'deleteSelected'])->name('bloggers.delete-selected');
    Route::resource('/bloggers', \App\Http\Controllers\Admin\BloggersController::class);

    Route::post('/remove-item-block', [\App\Http\Controllers\Admin\BannersController::class,'removeItem'])->name('banners.remove-item');
    Route::post('/banners/add-empty-item', [\App\Http\Controllers\Admin\BannersController::class,'addEmptyItem'])->name('banner.add-empty-item');
    Route::post('/banner-stat/export', [\App\Http\Controllers\Admin\AnalyticsController::class,'export'])->name('banner-stat.export');
    Route::resource('/banner-stat', \App\Http\Controllers\Admin\AnalyticsController::class);
    Route::resource('/banners', \App\Http\Controllers\Admin\BannersController::class);

    /** BLOG **/
    Route::post('/categories/collapse', [\App\Http\Controllers\Admin\CategoriesController::class,'collapse'])->name('set-collapse');
    Route::resource('/categories', \App\Http\Controllers\Admin\CategoriesController::class);
    Route::get('/category/articles-create-with-category', [\App\Http\Controllers\Admin\CategoriesController::class,'createArticleWithCategory'])->name('articles.create-with-category');
    Route::get('/category/{path}/{sub?}', [\App\Http\Controllers\Admin\CategoriesController::class,'category'])->where('path', '[a-z0-9-]+')->where('sub', '[a-z0-9-]+');
    Route::group(['prefix' => 'blog'], function () {
        Route::resource('/tags', \App\Http\Controllers\Admin\BlogTagsController::class);
        Route::post('/articles/delete-selected', [\App\Http\Controllers\Admin\BlogArticlesController::class,'deleteSelected'])->name('articles.delete-selected');
        Route::get('/article/search',[\App\Http\Controllers\Admin\BlogArticlesController::class,'search'])->name('article.search');

        Route::post('/articles/delete-gallery', [\App\Http\Controllers\Admin\BlogArticlesController::class,'deleteFromGallery'])->name('articles.delete-gallery');
        Route::post('/articles/add-gallery', [\App\Http\Controllers\Admin\BlogArticlesController::class,'addGallery'])->name('articles.add-gallery');
        Route::resource('/articles', \App\Http\Controllers\Admin\BlogArticlesController::class);
        Route::delete('/subscribe/delete', [\App\Http\Controllers\Admin\BlogSubscribeController::class, 'delete'])->name('subscribe.delete');
        Route::get('/subscribe/list', [\App\Http\Controllers\Admin\BlogSubscribeController::class,'list'])->name('subscribe.list');
    });

    Route::get('/subscribe', [\App\Http\Controllers\Admin\BlogSubscribeController::class,'index'])->name('subscribe.index');

    Route::get('/tag/binding',[\App\Http\Controllers\Admin\TagsController::class,'binding'])->name('tag.binding');
    Route::post('/tag/tie',[\App\Http\Controllers\Admin\TagsController::class,'tie'])->name('tag.tie');
    Route::get('/tag/search',[\App\Http\Controllers\Admin\TagsController::class,'search'])->name('tags.search');
    Route::resource('/tag',\App\Http\Controllers\Admin\TagsController::class);

    Route::get('/multimedia/files',[\App\Http\Controllers\Admin\FileManagerController::class,'file'])->name('multimedia.files');
    Route::get('/multimedia/images',[\App\Http\Controllers\Admin\FileManagerController::class,'image'])->name('multimedia.images');

    Route::get('/landing/search',[\App\Http\Controllers\Admin\LandingController::class,'search'])->name('landing.search');
    Route::resource('/landing', \App\Http\Controllers\Admin\LandingController::class);
});
/************************************ END ADMIN ***********************************************************************/

Route::group(['namespace' => 'Front'], function(){
    Route::get('/rss/{id}', [\App\Http\Controllers\Front\RssController::class,'indexUk']);
    Route::get('/sitemap.xml', [\App\Http\Controllers\Front\RssController::class,'sitemap']);
    Route::get('{lang}/rss/{id}', [\App\Http\Controllers\Front\RssController::class,'index']);
    Route::any('/tg/{id}', [\App\Http\Controllers\Front\AdController::class,'index'])->where('id', '^(?!api).*$');

    Route::any('/{any}', [\App\Http\Controllers\Front\HomeController::class,'index'])->where('any', '^(?!api).*$')->name('home');
});
/*******************************************************************/

app/Models/Category.php
<?php

namespace App\Models;

use Astrotomic\Translatable\Translatable;
use Cviebrock\EloquentSluggable\Sluggable;
use Cviebrock\EloquentSluggable\SluggableScopeHelpers;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Category
 * @package App\Models
 *
 * @property string $slug
 * @property string $image
 * @property string $path
 * @property string $creator
 * @property string $changer
 * @property integer $parent_id
 * @property integer $order
 * @property integer $agro_id
 * @property boolean $status
 * @property boolean $active
 * @property boolean $collapse
 *
 * @property BlogArticles[] $articles
 * @property BlogArticles[] $articlesInSubCategories
 * @property SideCategorySettings $setting
 */
class Category extends Model
{
    use HasFactory;

    use Sluggable;
    use Translatable;
    use SluggableScopeHelpers;

    protected $table = 'category';

    public $translationModel = 'App\Models\Translations\CategoryTranslation';

    public $translatedAttributes = [
        'title',
        'excerpt',
        'description',
        'h2',
        'meta_title',
        'meta_keywords',
        'meta_description'
    ];

    protected $fillable = [
        'slug',
        'image',
        'order',
        'status',
        'parent_id',
        'collapse',
        'agro_id',
        'path',
        'creator',
        'changer',
        'active'
    ];

    protected $casts = [
        'status'   => 'boolean',
        'active'   => 'boolean',
        'collapse' => 'boolean',
    ];

    const STATUS_NOT_ACTIVE = false;
    const STATUS_ACTIVE     = true;

    public function getDefaultTitleAttribute()
    {
        return $this->translateOrDefault()->title;
    }

    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'defaultTitle'
            ]
        ];
    }

    public static function getStatuses(): array
    {
        return [
            self::STATUS_NOT_ACTIVE => [
                'title'    => 'Не активная',
                'bg_color' => '#ff3838',
                'color'    => '#fdfdfd'
            ],
            self::STATUS_ACTIVE     => [
                'title'    => 'Активная',
                'bg_color' => '#49cc00',
                'color'    => 'white'
            ]
        ];
    }

    public function showStatus()
    {
        return '<span class="badge" style="color: ' . self::getStatuses()[$this->status]["color"] . '; background-color: ' . self::getStatuses()[$this->status]["bg_color"] . '">' . self::getStatuses()[$this->status]["title"] . '</span>';
    }

    public function scopeActive($query)
    {
        return $query->where('status', self::STATUS_ACTIVE);
    }

    /* Generate tree structure data */
    public function treeStructure()
    {
        $cat = $this;
        $data = cache()->rememberForever('treeStructure',function() use($cat){
            $collection = $cat->query()->withTranslation()
                ->get()
                ->toArray();

            $normalize = [];

            foreach ($collection as $item) {
                $normalize[$item['parent_id']][$item['id']] = $item;
            }
            if (!empty($normalize) && isset($normalize[0])) {
                $node = $normalize[0];

                $cat->treeNode($node, $normalize);
            } else {
                $node = $normalize;
            }

            return collect($node);
        });
        return $data;
    }

    public function treeNode(&$node, $normalize)
    {
        foreach ($node as $key => $item) {
            if (!isset($item['children'])) {
                $node[$key]['children'] = [];
            }

            if (array_key_exists($key, $normalize)) {
                $node[$key]['children'] = $normalize[$key];
                $this->treeNode($node[$key]['children'], $normalize);
            }
        }
    }

    public function parent()
    {
        return $this->belongsTo(self::class, 'parent_id');
    }

    private function getCategories($cat, $res = [])
    {
        if (isset($cat->parent->title)) {
            $res[] = $cat->parent->title;
            return $this->getCategories($cat->parent, $res);
        }

        return $res;
    }

    public function getNameWithPath()
    {
        $cat = $this;
        $data = cache()->rememberForever('getNameWithPath_'.$cat->id,function () use($cat){
            $arr = $cat->getCategories($cat);

            $arr = array_reverse($arr);

            $res = '';

            foreach ($arr as $item) {
                $res .= $item . ' > ';
            }

            $res .= $cat->title;

            return $res;
        });

        return $data;
    }

    /**
     * Публикаии в текущей категории, без учета вложинных подкатегория
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function articles()
    {
        return $this->hasMany(BlogArticles::class,'category_id','id');
    }

    /**
     * Подсчет количества публикаций в категории
     * @return int
     */
    public function countArticles(): int
    {
        return $this->articles()->active()->count();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function childs()
    {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    /**
     * Подсчет количества публикаций в категории с учетом всех подкатегорий
     * @return int
     */
    public function countArticlesInSubCategories(): int
    {
        $self  = $this;
        $count = 0;
        $count += $this->countArticles() +
            $self->childs()->get()
                ->sum(function (Category $category) {
                    return $category->countArticlesInSubCategories();
                });
        return $count;
    }

    public function getAllChildCategoryIds($children = null, $ids = [])
    {
        if ($children) {
            foreach ($children->get() as $child) {
                $ids[] = $child->id;
                $ids   = $this->getAllChildCategoryIds($child->childs(), $ids);
            }

        }

        return $ids;
    }

    /**
     * публикации в категории с учетом всех подкатегорий
     */
    public function articlesInSubCategories()
    {
        $ids   = [];
        $ids[] = $this->id;

        $ids = array_merge($ids, $this->getAllChildCategoryIds($this->childs()));

        return BlogArticles::query()
            ->leftJoin('blog_article_translations', 'blog_article_translations.blog_articles_id', '=', 'blog_articles.id')
            ->where('blog_article_translations.lang', Langs::getDefaultLangCode())
            ->where('blog_articles.status', BlogArticles::STATUS_ACTIVE)
            ->whereIn('blog_articles.category_id', $ids)
            ->select([
                'blog_articles.*',
                'blog_article_translations.name'
            ])
            ->get();
    }

    /**
     * Подсчет количества категорий с учетом всех подкатегорий
     * @return int
     */
    public function countSubCategories(): int
    {
        $self  = $this;
        $count = 0;
        $count += $this->childs()->count() +
            $self->childs()->get()
                ->sum(function (Category $category) {
                    return $category->countSubCategories();
                });
        return $count;
    }

    public function setting()
    {
        return $this->hasOne(SideCategorySettings::class,'category_id','id');
    }
}

resources/views/admin/categories/___articles-list.blade.php
@extends('layouts.admin.app')

@section('content')
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('admin')}}">Панель управления</a></li>
            <li class="breadcrumb-item active" aria-current="page">Рубрики</li>
            <li class="breadcrumb-item active" aria-current="page">{{$category->title}}</li>
            <li class="breadcrumb-item active" aria-current="page">Публикации</li>
        </ol>
    </nav>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <?php
                    $url = \Illuminate\Support\Facades\Request::url();

                    $parts = explode('admin/category/',$url);
                ?>
                <a href="{{route('articles.create-with-category',['path' => $parts[1] ?? null])}}" class="btn btn-primary float-right">
                    <i class="fa fa-plus"></i>
                    Добавить
                </a>
            </div>
            <div class="card-body">
{{--                <form action="" method="get">--}}
{{--                    <div class="form-row">--}}
{{--                        <div class="form-group col-md-2">--}}
{{--                            <label>Статус</label>--}}
{{--                            <select name="status" class="select2 form-control m-t-15">--}}
{{--                                <option value="">---</option>--}}
{{--                                @foreach(\App\Models\Category::getStatuses() as $key => $item)--}}
{{--                                    <option value="{{$key}}" @if(old('status', request()->input('status')) == (string)$key) selected @endif>{{$item}}</option>--}}
{{--                                @endforeach--}}
{{--                            </select>--}}
{{--                        </div>--}}

{{--                        <div class="form-group col-md-2">--}}
{{--                            <label>Поиск</label>--}}
{{--                            <input type="text" class="form-control" name="name" value="{{old('name', request()->input('name'))}}">--}}
{{--                        </div>--}}

{{--                        <div class="form-group col-md-1">--}}
{{--                            <label for="inputPassword4">&nbsp;</label>--}}
{{--                            <button type="submit" class="btn btn-success form-control text-white">Фильтровать</button>--}}
{{--                        </div>--}}
{{--                        <div class="form-group col-md-1">--}}
{{--                            <label for="inputPassword4">&nbsp;</label>--}}
{{--                            <a href="{{ route('category.index') }}" class="btn btn-danger form-control text-white">Сбросить</a>--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                </form>--}}

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Название</th>
                            <th>Сортировка</th>
                            <th>Статус</th>
                            <th>Дата публикации</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($articles as $item)
                            <tr data-id="{{$item->id}}">
                                <td>{{$item->id}}</td>
                                <td>
                                    @permission('blog__articles__edit')
                                    <a href="{{ route('articles.edit', $item->id) }}">
                                        {{$item->name}}
                                    </a>
                                    @else
                                        {{$item->name}}
                                    @endpermission
                                </td>
                                <td>{{$item->order}}</td>
                                <td>{!! $item->showStatus() !!}</td>
                                <td>{{\Carbon\Carbon::create($item->public_date)->format('d-m-Y H:i')}}</td>
                                <td>
                                    <div style="display: flex">
                                        <div style="margin-left: 10px">
                                            <form action="{{ route('articles.destroy', $item->id) }}" method="POST">

                                                <a href="/catalog/{{$item->path}}" target="_blank" class="btn btn-info btn-xs" title="Посмотреть на сайте"><i class="fa fa-eye"></i></a>

                                                <a href="{{ route('articles.edit', $item->id) }}" class="btn btn-xs btn-primary">
                                                    <i class="fas fa-edit fa-lg"></i>
                                                </a>

                                                @csrf
                                                @method('DELETE')

                                                <a href="javascript:void(0)" title="Удалить" class="btn btn-danger btn-xs delete-item-btn text-white">
                                                    <i class="fas fa-trash"></i>
                                                </a>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

                {{ $articles->appends(request()->all())->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script>
        $(document).ready(() => {
            $('.delete-item-btn').on('click',function() {
                if(confirm('Вы пытаетесь удалить запись?')){
                    $(this).closest('form').submit();
                }
            });
        });
    </script>
@endpush

resources/views/admin/categories/_form.blade.php
<div class="form-group row">
    <label class="col-md-3 text-right" for="page_title_{{ $lang }}">Название</label>
    <div class="col-md-9">
        <input type="text" name="page_data[{{ $lang }}][title]" value="{{ old('page_data.' . $lang . '.title', $data[$lang]['title'] ?? '') }}" id="page_title_{{ $lang }}" class="form-control{{ $errors->has('page_data.' . $lang . '.title') ? ' is-invalid' : '' }}">

        @if ($errors->has('page_data.' . $lang . '.title'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('page_data.' . $lang . '.title') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group row">
    <label class="col-md-3 text-right" for="page_h2_{{ $lang }}">H2</label>
    <div class="col-md-9">
        <input type="text" name="page_data[{{ $lang }}][h2]" value="{{ old('page_data.' . $lang . '.h2', $data[$lang]['h2'] ?? '') }}" id="page_h2_{{ $lang }}" class="form-control{{ $errors->has('page_data.' . $lang . '.h2') ? ' is-invalid' : '' }}">

        @if ($errors->has('page_data.' . $lang . '.h2'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('page_data.' . $lang . '.h2') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group row">
    <label class="col-md-3 text-right" for="page_description_{{ $lang }}">Описание</label>
    <div class="col-md-9">
        <textarea
            name="page_data[{{ $lang }}][description]"
            id="page_description_{{ $lang }}"
            class="summernote editor {{ $errors->has('page_data.' . $lang . '.description') ? ' is-invalid' : '' }}"
            cols="30"
            rows="10"
        >{{ old('page_data.' . $lang . '.description', $data[$lang]['description'] ?? '') }}</textarea>

        @if ($errors->has('page_data.' . $lang . '.description'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('page_data.' . $lang . '.description') }}</strong>
            </span>
        @endif
    </div>
</div>

{{--<div class="form-group row">--}}
{{--    <label class="col-md-3 text-right" for="page_excerpt_{{ $lang }}">Скрытое описание</label>--}}
{{--    <div class="col-md-9">--}}
{{--        <textarea--}}
{{--            name="page_data[{{ $lang }}][excerpt]"--}}
{{--            id="page_excerpt_{{ $lang }}"--}}
{{--            class="summernote editor {{ $errors->has('page_data.' . $lang . '.excerpt') ? ' is-invalid' : '' }}"--}}
{{--            cols="30"--}}
{{--            rows="10"--}}
{{--        >{{ old('page_data.' . $lang . '.excerpt', $data[$lang]['excerpt'] ?? '') }}</textarea>--}}

{{--        @if ($errors->has('page_data.' . $lang . '.excerpt'))--}}
{{--            <span class="invalid-feedback" role="alert">--}}
{{--                <strong>{{ $errors->first('page_data.' . $lang . '.excerpt') }}</strong>--}}
{{--            </span>--}}
{{--        @endif--}}
{{--    </div>--}}
{{--</div>--}}

<div class="form-group row">
    <label class="col-md-3 text-right" for="page_meta_title_{{ $lang }}">Meta title</label>
    <div class="col-md-9">
        <input type="text" name="page_data[{{ $lang }}][meta_title]" value="{{ old('page_data.' . $lang . '.meta_title', $data[$lang]['meta_title'] ?? '') }}" id="page_meta_title_{{ $lang }}" class="form-control{{ $errors->has('page_data.' . $lang . '.meta_title') ? ' is-invalid' : '' }}">

        @if ($errors->has('page_data.' . $lang . '.meta_title'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('page_data.' . $lang . '.meta_title') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group row">
    <label class="col-md-3 text-right" for="page_meta_description_{{ $lang }}">Meta description</label>
    <div class="col-md-9">
        <input type="text" name="page_data[{{ $lang }}][meta_description]" value="{{ old('page_data.' . $lang . '.meta_description', $data[$lang]['meta_description'] ?? '') }}" id="page_meta_description_{{ $lang }}" class="form-control{{ $errors->has('page_data.' . $lang . '.meta_description') ? ' is-invalid' : '' }}">

        @if ($errors->has('page_data.' . $lang . '.meta_description'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('page_data.' . $lang . '.meta_description') }}</strong>
            </span>
        @endif
    </div>
</div>

resources/views/admin/categories/categories-list.blade.php
@extends('layouts.admin.app')

@section('content')
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('admin')}}">Панель управления</a></li>
            <li class="breadcrumb-item active" aria-current="page">Рубрики</li>
            <li class="breadcrumb-item active" aria-current="page">{{$category->title}}</li>
        </ol>
    </nav>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                @permission('categories__categories__edit')
                <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-primary float-right" title="Редактировать рубрику">
                    <i class="fas fa-edit fa-lg"></i>
                    Редактировать рубрику
                </a>
                @endpermission
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Название</th>
                            <th>Сортировка</th>
                            <th>Статус</th>
                            <th>Дата создания</th>
                            <th style="min-width: 150px"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($subCategories as $item)
                            <tr data-id="{{$item->id}}">
                                <td>{{$item->id}}</td>
                                <td>
                                    <a href="/admin/category/{{$item->path}}">
                                        {{$item->title}}
                                    </a>
                                </td>
                                <td>{{$item->order}}</td>
                                <td>{!! $item->showStatus() !!}</td>
                                <td>{{$item->created_at->format('d.m.Y')}}</td>
                                <td>
                                    <div style="display: flex">
                                        <div style="margin-left: 10px">
                                            <form action="{{ route('categories.destroy', $item->id) }}" method="POST">

{{--                                                <a href="/catalog/{{$item->path}}" target="_blank" class="btn btn-info btn-xs" title="Посмотреть на сайте"><i class="fa fa-eye"></i></a>--}}

                                                @permission('categories__categories__edit')
                                                <a href="{{ route('categories.edit', $item->id) }}" class="btn btn-xs btn-primary" title="Редактировать рубрику">
                                                    <i class="fas fa-edit fa-lg"></i>
                                                </a>
                                                @endpermission

                                                @csrf
                                                @method('DELETE')
                                                @permission('categories__categories__delete')
                                                <a href="javascript:void(0)" title="Удалить" class="btn btn-danger btn-xs delete-item-btn text-white">
                                                    <i class="fas fa-trash"></i>
                                                </a>
                                                @endpermission
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

                {{ $subCategories->appends(request()->all())->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script>
        $(document).ready(() => {
            $('.delete-item-btn').on('click',function() {
                if(confirm('Вы пытаетесь удалить запись?')){
                    $(this).closest('form').submit();
                }
            });
        });
    </script>
@endpush