routes/web.php
<?php

use App\Http\Middleware\LocaleMiddleware;
use Illuminate\Support\Facades\Route;

/* @var $localeMiddleware LocaleMiddleware */
$localeMiddleware = app( LocaleMiddleware::class);

\Illuminate\Support\Facades\Auth::routes();

Route::get('/admin/cache-clear',function (){
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');

    return redirect()->back()->with('success','Кеш успешно очищено!');
})->name('cache-clear');

Route::get('/admin/rename-index',function (){
//   $oldTagNameUk = "Індекс АПК";
//   $oldTagNameRu = "Индекс АПК";
//   $replaceUk = "Регіони";
//   $replaceRu = "Регионы";
//
//   $modelUk = \App\Models\Translations\BlogArticleTranslation::query()
//       ->where('tags','like','%'.$oldTagNameUk.'%')
//       ->get();
//
//   foreach ($modelUk as $item){
//       $tags = $item->tags;
//       $item->tags = mb_str_replace($oldTagNameUk,$replaceUk,$tags);
//       $item->save();
//   }
//
//    $modelRu = \App\Models\Translations\BlogArticleTranslation::query()
//        ->where('tags','like','%'.$oldTagNameRu.'%')
//        ->get();
//
//    foreach ($modelRu as $item){
//        $tags = $item->tags;
//        $item->tags = mb_str_replace($oldTagNameRu,$replaceRu,$tags);
//        $item->save();
//    }
//
//    dd('Ready');

});

//Route::get('rss-generate', function (){
//    \Illuminate\Support\Facades\Artisan::call('rss:generate');
//
//    dd('RSS is generated!');
//});
//
//Route::get('sitemap-gen',function (){
//    \Illuminate\Support\Facades\Artisan::call('sitemap:generate');
//    dd('ready');
//});
//
//Route::get('article-alt-generate',function (){
//    \Illuminate\Support\Facades\Artisan::call('altEmpty:generate');
//    dd('ready');
//});
//
//Route::get('parser-meta-tags-start',function (){
//    \Illuminate\Support\Facades\Artisan::call('ParserMetaTags:start');
//    dd('ready');
//});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::any('/admin/login', [\App\Http\Controllers\Admin\HomeController::class,'login'])->name('admin.login');

/*********************************************** ADMIN ****************************************************************/
Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function () {
    Route::post('/export-table', [\App\Http\Controllers\Admin\ExportTableController::class,'export'])->name('export-table');
    Route::get('/', [\App\Http\Controllers\Admin\HomeController::class,'index'])->name('admin');
    Route::resource('/users-admin', \App\Http\Controllers\Admin\UserAdminController::class);
    Route::resource('/access-groups', \App\Http\Controllers\Admin\AccessGroupsController::class);
    Route::get('/users/{id}/{tab}', [\App\Http\Controllers\Admin\UsersController::class,'getTab'])->where('tab', '[a-z0-9-]+');
    Route::post('/users-change-status', [\App\Http\Controllers\Admin\UsersController::class,'changeStatus'])->name('user.change-status');
    Route::resource('/users', \App\Http\Controllers\Admin\UsersController::class);
    Route::post('/pages/menu/add-item', [\App\Http\Controllers\Admin\PagesController::class,'addItem'])->name('page.add-item');
    Route::resource('/pages', \App\Http\Controllers\Admin\PagesController::class);
    Route::post('menu/toggle-collapse', [\App\Http\Controllers\Admin\MenuController::class,'toggleCollapse'])->name('menu.toggle-collapse');
    Route::post('menu/move', [\App\Http\Controllers\Admin\MenuController::class,'move']);
    Route::post('menu/rebuild', [\App\Http\Controllers\Admin\MenuController::class,'rebuild']);
    Route::post('menu/add-item', [\App\Http\Controllers\Admin\MenuController::class,'addItem'])->name('menu.add-item');
    Route::post('menu/delete-menu', [\App\Http\Controllers\Admin\MenuController::class,'deleteMenu'])->name('menu.delete-menu');
    Route::post('menu/add-menu', [\App\Http\Controllers\Admin\MenuController::class,'addMenu'])->name('menu.add-menu');
    Route::resource('/menu', \App\Http\Controllers\Admin\MenuController::class);
    Route::resource('/faq', \App\Http\Controllers\Admin\FaqController::class);
    Route::get('settings/{tab}', [\App\Http\Controllers\Admin\SettingsController::class,'index'])->name('add-notice')->where('tab', '[a-z0-9-]+');
    Route::post('settings/save', [\App\Http\Controllers\Admin\SettingsController::class,'save'])->name('settings.save');
    Route::post('/request/status/change', [\App\Http\Controllers\Admin\RequestController::class,'changeStatus'])->name('request.status-change');
    Route::resource('/request', \App\Http\Controllers\Admin\RequestController::class);

    Route::post('/bloggers/delete-selected', [\App\Http\Controllers\Admin\BloggersController::class,'deleteSelected'])->name('bloggers.delete-selected');
    Route::resource('/bloggers', \App\Http\Controllers\Admin\BloggersController::class);

    Route::post('/remove-item-block', [\App\Http\Controllers\Admin\BannersController::class,'removeItem'])->name('banners.remove-item');
    Route::post('/banners/add-empty-item', [\App\Http\Controllers\Admin\BannersController::class,'addEmptyItem'])->name('banner.add-empty-item');
    Route::post('/banner-stat/export', [\App\Http\Controllers\Admin\AnalyticsController::class,'export'])->name('banner-stat.export');
    Route::resource('/banner-stat', \App\Http\Controllers\Admin\AnalyticsController::class);
    Route::resource('/banners', \App\Http\Controllers\Admin\BannersController::class);

    /** BLOG **/
    Route::post('/categories/collapse', [\App\Http\Controllers\Admin\CategoriesController::class,'collapse'])->name('set-collapse');
    Route::resource('/categories', \App\Http\Controllers\Admin\CategoriesController::class);
    Route::get('/category/articles-create-with-category', [\App\Http\Controllers\Admin\CategoriesController::class,'createArticleWithCategory'])->name('articles.create-with-category');
    Route::get('/category/{path}/{sub?}', [\App\Http\Controllers\Admin\CategoriesController::class,'category'])->where('path', '[a-z0-9-]+')->where('sub', '[a-z0-9-]+');
    Route::group(['prefix' => 'blog'], function () {
        Route::resource('/tags', \App\Http\Controllers\Admin\BlogTagsController::class);
        Route::post('/articles/delete-selected', [\App\Http\Controllers\Admin\BlogArticlesController::class,'deleteSelected'])->name('articles.delete-selected');
        Route::get('/article/search',[\App\Http\Controllers\Admin\BlogArticlesController::class,'search'])->name('article.search');

        Route::post('/articles/delete-gallery', [\App\Http\Controllers\Admin\BlogArticlesController::class,'deleteFromGallery'])->name('articles.delete-gallery');
        Route::post('/articles/add-gallery', [\App\Http\Controllers\Admin\BlogArticlesController::class,'addGallery'])->name('articles.add-gallery');
        Route::resource('/articles', \App\Http\Controllers\Admin\BlogArticlesController::class);
        Route::delete('/subscribe/delete', [\App\Http\Controllers\Admin\BlogSubscribeController::class, 'delete'])->name('subscribe.delete');
        Route::get('/subscribe/list', [\App\Http\Controllers\Admin\BlogSubscribeController::class,'list'])->name('subscribe.list');
    });

    Route::get('/subscribe', [\App\Http\Controllers\Admin\BlogSubscribeController::class,'index'])->name('subscribe.index');

    Route::get('/tag/binding',[\App\Http\Controllers\Admin\TagsController::class,'binding'])->name('tag.binding');
    Route::post('/tag/tie',[\App\Http\Controllers\Admin\TagsController::class,'tie'])->name('tag.tie');
    Route::get('/tag/search',[\App\Http\Controllers\Admin\TagsController::class,'search'])->name('tags.search');
    Route::resource('/tag',\App\Http\Controllers\Admin\TagsController::class);

    Route::get('/multimedia/files',[\App\Http\Controllers\Admin\FileManagerController::class,'file'])->name('multimedia.files');
    Route::get('/multimedia/images',[\App\Http\Controllers\Admin\FileManagerController::class,'image'])->name('multimedia.images');

    Route::get('/landing/search',[\App\Http\Controllers\Admin\LandingController::class,'search'])->name('landing.search');
    Route::resource('/landing', \App\Http\Controllers\Admin\LandingController::class);
});
/************************************ END ADMIN ***********************************************************************/

Route::group(['namespace' => 'Front'], function(){
    Route::get('/rss/{id}', [\App\Http\Controllers\Front\RssController::class,'indexUk']);
    Route::get('/sitemap.xml', [\App\Http\Controllers\Front\RssController::class,'sitemap']);
    Route::get('{lang}/rss/{id}', [\App\Http\Controllers\Front\RssController::class,'index']);
    Route::any('/tg/{id}', [\App\Http\Controllers\Front\AdController::class,'index'])->where('id', '^(?!api).*$');

    Route::any('/{any}', [\App\Http\Controllers\Front\HomeController::class,'index'])->where('any', '^(?!api).*$')->name('home');
});
/*******************************************************************/

app/Http/Controllers/Admin/TagsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Langs;
use App\Models\NewTag;
use App\Models\Tags;
use App\Models\Translations\NewTagTranslation;
use Cviebrock\EloquentSluggable\Services\SlugService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class TagsController extends Controller
{

    public function index(Request $request)
    {
        // access
        if(! permissions('tags__tags__view')) abort(404);

        $name = $request->get('name');

        $model = NewTag::query()
            ->leftJoin('new_tag_translations','new_tag_translations.new_tag_id', '=', 'new_tags.id')
            ->where('new_tag_translations.lang',Langs::getDefaultLangCode())
            ->select([
                'new_tags.*',
                'new_tag_translations.name AS tagName'
            ])
            ->where(function ($q) use ($name) {
                if ($name != '') {
                    $q->where('new_tag_translations.name', 'like', '%' . $name . '%');
                }
            })
            ->paginate(20);

        return view('admin.tags.index', [
            'model' => $model
        ]);
    }

    public function create()
    {
        // access
        if (!permissions('tags__tags__create'))
            abort(404);

        $model = new NewTag();

        $localizations = Langs::getLangsWithTitle();

        return view('admin.tags.create', [
            'model'         => $model,
            'localizations' => $localizations
        ]);
    }

    public function store(Request $request)
    {
        // access
        if (!permissions('tags__tags__create')) {
            return redirect()->back()->with('error', 'У вас нет прав на выполнение данного действия!');
        };

        $model = new NewTag();

        DB::beginTransaction();

        try {
            if (empty($request->input('slug', ''))) {
                $request->merge(array('slug' => SlugService::createSlug(NewTag::class, 'slug', $request->input('page_data.' . Langs::getDefaultLangCode() . '.name'))));
            }

            $model->fill($request->all());

            if (!$model->save()) {
                DB::rollBack();
            }

            foreach (Langs::getLangsWithTitle() as $lang => $item) {
                $data = $request->input('page_data.' . $lang, []);

                $constructorData = $request->get('constructorData');
                $model->translateOrNew($lang)->fill(array_merge($data, $constructorData[$lang] ?? []));

                if (!$model->save()) {
                    DB::rollBack();
                }
            }
        } catch (\Throwable $e) {
            DB::rollBack();

            return redirect()->back()->with('error', 'Ошибка! ' . $e->getMessage());
        }

        DB::commit();

        return redirect()->route('tag.index')->with('success', 'Тег успешно добавлен!');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        // access
        if (!permissions('tags__tags__edit'))
            abort(404);

        $model = NewTag::query()->where('id', $id)->first();

        $localizations = Langs::getLangsWithTitle();

        return view('admin.tags.edit', [
            'model'         => $model,
            'data'          => $model->getTranslationsArray(),
            'localizations' => $localizations,
        ]);
    }

    public function update(Request $request, $id)
    {
        // access
        if (!permissions('tags__tags__edit')) {
            return redirect()->back()->with('error', 'У вас нет прав на выполнение данного действия!');
        };

        /* @var $model NewTag */
        $model = NewTag::query()->where('id', $id)->first();

        DB::beginTransaction();

        try {
            $model->fill($request->all());

            if (!$model->save()) {
                DB::rollBack();
            }

            $model->deleteTranslations();

            foreach (Langs::getLangsWithTitle() as $lang => $item) {
                $data = $request->input('page_data.' . $lang, []);

                $constructorData = $request->get('constructorData');
                $model->translateOrNew($lang)->fill(array_merge($data, $constructorData[$lang] ?? []));

                if (!$model->save()) {
                    DB::rollBack();
                }
            }
        } catch (\Throwable $e) {
            DB::rollBack();

            return redirect()->route('tag.index')->with('error', 'Ошибка! ' . $e->getMessage());
        }

        DB::commit();

        return redirect()->back()->with('success', 'Тег успешно обновлен!');
    }

    public function destroy($id)
    {
        // access
        if (!permissions('tags__tags__delete')) {
            return redirect()->back()->with('error', 'У вас нет прав на выполнение данного действия!');
        };

        $model = NewTag::query()->where('id', $id)->first();
        $model->deleteTranslations();
        NewTag::query()->where('id', $id)->delete();

        return redirect()->back()->with('success', 'Тег успешно удален!');
    }

    /**
     * @param Request $request
     * @return array
     */
    public function search(Request $request)
    {
        $term = $request->get('term');
        $q = $term['term'];

        $items = NewTag::query()
            ->leftJoin('new_tag_translations','new_tag_translations.new_tag_id','=','new_tags.id')
//            ->where('new_tag_translations.lang',Langs::getDefaultLangCode())
            ->select([
                'new_tags.id',
                'new_tag_translations.name'
            ])
            ->where('new_tag_translations.name','like','%' . $q . '%')
            ->get()
            ->toArray();

        return [
            'items' => $items
        ];
    }

    public function binding(Request $request)
    {
        $data = [];

        $data['ru'] = Tags::query()
            ->where('related',0)
            ->where('lang','ru')
            ->pluck('name','id')
            ->toArray();

        $data['uk'] = Tags::query()
            ->where('related',0)
            ->where('lang','uk')
            ->pluck('name','id')
            ->toArray();

        if($request->has('a')){
            $data['ru'] = Tags::query()
                ->where('related',0)
                ->where('lang','ru')
                ->where('name', 'LIKE', $request->get('a').'%')
                ->pluck('name','id')
                ->toArray();
        }

        if($request->has('b')){
            $data['uk'] = Tags::query()
                ->where('related',0)
                ->where('lang','uk')
                ->where('name', 'LIKE', $request->get('b').'%')
                ->pluck('name','id')
                ->toArray();
        }

        return view('admin.tags.binding', [
            'data' => $data
        ]);
    }

    public function tie(Request $request)
    {
        if($request->has('ruId') && $request->has('ukId')){
            $ruTag = Tags::query()->where('id',$request->get('ruId'))->where('related',0)->first();
            $ukTag = Tags::query()->where('id',$request->get('ukId'))->where('related',0)->first();

            if($ruTag && $ukTag){
                $newTag = new NewTag();
                $newTag->slug = SlugService::createSlug(NewTag::class, 'slug', $ukTag->name);

                if($newTag->save()){
                    $newTagTransUk = new NewTagTranslation();
                    $newTagTransUk->new_tag_id = $newTag->id;
                    $newTagTransUk->lang = 'uk';
                    $newTagTransUk->name = $ukTag->name;
                    $newTagTransUk->save();

                    $newTagTransRu = new NewTagTranslation();
                    $newTagTransRu->new_tag_id = $newTag->id;
                    $newTagTransRu->lang = 'ru';
                    $newTagTransRu->name = $ruTag->name;
                    $newTagTransRu->save();

                    $ruTag->related = 1;
                    $ruTag->save();

                    $ukTag->related = 1;
                    $ukTag->save();

                   return [
                       'success' => true
                   ];
                }
            }
        }

        return [
            'success' => false,
            'message' => 'Не удалось связать теги, возможно они уже связанные, перезагрузите страничку.'
        ];
    }
}

resources/views/admin/tags/_form.blade.php
<div class="form-group row">
    <label class="col-md-3 text-right" for="page_slug">Slug</label>
    <div class="col-md-9">
        <input type="text" name="slug" value="{{ old('slug', $model->slug ?? '') }}" id="page_slug" class="form-control{{ $errors->has('slug') ? ' is-invalid' : '' }}">

        @if ($errors->has('slug'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('slug') }}</strong>
            </span>
        @endif
    </div>
</div>

@push('styles')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css">
    <style>
        /*-- ==============================================================
        Switches
        ============================================================== */
        .material-switch {
            line-height: 3em;
        }
        .material-switch > input[type="checkbox"] {
            display: none;
        }

        .material-switch > label {
            cursor: pointer;
            height: 0px;
            position: relative;
            width: 40px;
        }

        .material-switch > label::before {
            background: rgb(0, 0, 0);
            box-shadow: inset 0px 0px 10px rgba(0, 0, 0, 0.5);
            border-radius: 8px;
            content: '';
            height: 16px;
            margin-top: -8px;
            position:absolute;
            opacity: 0.3;
            transition: all 0.4s ease-in-out;
            width: 40px;
        }
        .material-switch > label::after {
            background: rgb(255, 255, 255);
            border-radius: 16px;
            box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.3);
            content: '';
            height: 24px;
            left: -4px;
            margin-top: -8px;
            position: absolute;
            top: -4px;
            transition: all 0.3s ease-in-out;
            width: 24px;
        }
        .material-switch > input[type="checkbox"]:checked + label::before {
            background: inherit;
            opacity: 0.5;
        }
        .material-switch > input[type="checkbox"]:checked + label::after {
            background: inherit;
            left: 20px;
        }

        .select2-container--default .select2-selection--multiple .select2-selection__choice {
            background-color: #5897fb !important;
            border: 1px solid #5897fb !important;
        }

        .select2-container--default .select2-selection--multiple .select2-selection__choice__remove {
            color: #fff !important;
        }

        .select2-container--classic .select2-selection--multiple .select2-selection__choice, .select2-container--default .select2-selection--multiple .select2-selection__choice, .select2-container--default .select2-selection--multiple .select2-selection__choice__remove {
            background-color:#5897fb !important;
        }

        .select2-container--default .select2-selection--multiple {
            border: 1px solid #e9ecef;
        }

        .select2-container--default.select2-container--focus .select2-selection--multiple {
            border: 1px solid #e9ecef;
            color: #3e5569;
            background-color: #fff;
            border-color: rgba(0,0,0,0.25);
            outline: 0;
            box-shadow: 0 0 0 0.2rem rgb(0 123 255 / 25%);
        }
    </style>
@endpush

@push('scripts')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(() => {

        });
    </script>
@endpush

resources/views/admin/tags/create.blade.php
@extends('layouts.admin.app')

@section('content')
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('admin')}}">Панель управления</a></li>
            <li class="breadcrumb-item"><a href="{{route('tag.index')}}">Теги</a></li>
            <li class="breadcrumb-item active" aria-current="page">Добавить</li>
        </ol>
    </nav>

    <form class="form-horizontal" method="POST" action="{{ route('tag.store') }}">
        @csrf

        <div class="row">
            <div class="col-md-12">
                <div class="card">

                    <div class="card-header">
                        <ul class="nav nav-tabs" id="myTab" role="tablist" style="margin-bottom: -10px;border-bottom: none">
                            <li class="nav-item">
                                <a class="nav-link active" id="main-tab" data-toggle="tab" href="#main" role="tab" aria-controls="main" aria-selected="true">Информация</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="seo-tab" data-toggle="tab" href="#seo" role="tab" aria-controls="seo" aria-selected="false">SEO</a>
                            </li>
                        </ul>
                    </div>

                    <div class="card-body">
                        <div class="tab-content" id="myTabContent">
                            {{----------------------------- MAIN TAB -----------------------------------------}}
                            <div class="tab-pane fade show active" id="main" role="tabpanel" aria-labelledby="main-tab">
                                <ul class="nav nav-tabs" role="tablist">
                                    @foreach($localizations as $key => $lang)
                                        <li class="nav-item">
                                            <a class="nav-link @if(app()->getLocale() == $key) active @endif" data-toggle="tab" href="#main_lang_{{ $key }}" role="tab">
                                                <span class="hidden-sm-up"></span> <span class="hidden-xs-down">{{ $lang }}</span>
                                            </a>
                                        </li>
                                    @endforeach
                                </ul>

                                <br>
                                <div class="tab-content">
                                    @foreach($localizations as $key => $catLang)
                                        <div class="tab-pane p-t-20 p-b-20  @if(app()->getLocale() == $key) active @endif" id="main_lang_{{ $key }}" role="tabpanel">
                                            @include('admin.tags.tabs._main',[
                                               'lang' => $key,
                                               'model' => $model
                                            ])
                                        </div>
                                    @endforeach

                                    @include('admin.tags._form',['model' => $model])
                                </div>
                            </div>

                            {{----------------------------- SEO TAB -----------------------------------------}}
                            <div class="tab-pane fade" id="seo" role="tabpanel" aria-labelledby="seo-tab">
                                <ul class="nav nav-tabs" role="tablist">
                                    @foreach($localizations as $key => $lang)
                                        <li class="nav-item">
                                            <a class="nav-link @if(app()->getLocale() == $key) active @endif" data-toggle="tab" href="#seo_lang_{{ $key }}" role="tab">
                                                <span class="hidden-sm-up"></span> <span class="hidden-xs-down">{{ $lang }}</span>
                                            </a>
                                        </li>
                                    @endforeach
                                </ul>

                                <br>
                                <div class="tab-content tabcontent-border">
                                    @foreach($localizations as $key => $catLang)
                                        <div class="tab-pane p-t-20 p-b-20  @if(app()->getLocale() == $key) active @endif" id="seo_lang_{{ $key }}" role="tabpanel">
                                            @include('admin.tags.tabs._seo',[
                                               'lang' => $key
                                            ])
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>

                        <input type="submit" value="Сохранить" class="btn btn-success text-white float-right">

                    </div>
                </div>
            </div>
        </div>

    </form>
@endsection

resources/views/admin/tags/index.blade.php
@extends('layouts.admin.app')

@section('content')
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route('admin')}}">Панель управления</a></li>
            <li class="breadcrumb-item active" aria-current="page">Теги</li>
        </ol>
    </nav>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                @permission('tags__tags__create')
                    <a href="{{route('tag.create')}}" class="btn btn-primary float-right">
                        <i class="fa fa-plus"></i>
                        Добавить
                    </a>
                @endpermission

                <a href="{{route('tag.binding')}}" class="btn btn-info float-right" style="margin-right: 15px" title="Сопоставить теги">
                    <i class="fa fa-arrows-h"></i>
                </a>
            </div>
            <div class="card-body">
                <form action="" method="get">
                    <div class="form-row">

                        <div class="form-group col-md-2">
                            <label>Поиск</label>
                            <input type="text" class="form-control" name="name" value="{{old('name', request()->input('name'))}}">
                        </div>

                        <div class="form-group col-md-1">
                            <label for="inputPassword4">&nbsp;</label>
                            <button type="submit" class="btn btn-success form-control text-white">Фильтровать</button>
                        </div>
                        <div class="form-group col-md-1">
                            <label for="inputPassword4">&nbsp;</label>
                            <a href="{{ route('tag.index') }}" class="btn btn-danger form-control text-white">Сбросить</a>
                        </div>
                    </div>
                </form>

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Название</th>
                            <th>Slug</th>
                            <th style="min-width: 150px">Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($model as $item)
                            <tr data-id="{{$item->id}}">
                                <td>{{$item->id}}</td>
                                <td>
                                    @permission('tags__tags__edit')
                                        <a href="{{ route('tag.edit', $item->id) }}">
                                            {{$item->name}}
                                        </a>
                                    @else
                                        {{$item->name}}
                                    @endpermission
                                </td>
                                <td>{{$item->slug}}</td>
                                <td>
                                    <div style="display: flex">
                                        <div style="margin-left: 10px">
                                            <form action="{{ route('tag.destroy', $item->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')

                                                @permission('tags__tags__delete')
                                                    <a href="javascript:void(0)" title="Удалить" class="btn btn-danger btn-xs delete-item-btn text-white">
                                                        <i class="fas fa-trash"></i>
                                                    </a>
                                                @endpermission
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

                {{ $model->appends(request()->all())->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script>
        $(document).ready(() => {
            $('.delete-item-btn').on('click',function() {
                if(confirm('Вы пытаетесь удалить запись?')){
                    $(this).closest('form').submit();
                }
            });
        });
    </script>
@endpush